export default {
    //current
    PUT_CURRENT_NAV_TYPE: "PUT_CURRENT_NAV_TYPE",


    //items
    RECEIVE_ITEMS: "RECEIVE_ITEMS",
    ADD_ITEM: "ADD_ITEM",
    EDIT_ITEM: "EDIT_ITEM",

    //bag_items
    RECEIVE_BAG_ITEMS: "RECEIVE_BAG_ITEMS",
    ADD_BAG_ITEM: "ADD_BAG_ITEM",

    //schedules
    RECEIVE_SCHEDULES: "RECEIVE_SCHEDULES",
    ADD_SCHEDULE: "ADD_SCHEDULE",
    EDIT_SCHEDULE: "EDIT_SCHEDULE",


    //quests
    REQUEST_QUESTS: "REQUEST_QUESTS",
    RECEIVE_QUESTS: "RECEIVE_QUESTS",

    COMPLETE_QUEST: "COMPLETE_QUEST",
    CANCEL_COMPLETE_QUEST: "CANCEL_COMPLETE_QUEST",
    EDIT_QUEST: "EDIT_QUEST",
    ADD_QUEST : "ADD_QUEST"
};
